apiVersion: v1
kind: Service
metadata:
  name: {{ include "mnist_chart.fullname" . }}
  labels:
    {{- include "mnist_chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.metrics_port }}
      targetPort: {{ .Values.service.metrics_target_port }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "mnist_chart.selectorLabels" . | nindent 4 }}
