torchserve_image: mnist:v0.1.0

namespace: torchserve

torchserve:
  management_port: 8081
  inference_port: 8080
  metrics_port: 8082
  n_gpu: 1
  n_cpu: 1
  memory_limit: 4Gi
  memory_request: 1Gi

torchingress:
  host: test.mnist.com

deployment:
  replicas: 1